/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package carnero.cgeo;

public final class R {
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int skin=0x7f010000;
    }
    public static final class color {
        public static final int background_dark=0x7f040002;
        public static final int background_dark_notice=0x7f040004;
        public static final int background_dark_transparent=0x7f040006;
        public static final int background_light=0x7f040003;
        public static final int background_light_notice=0x7f040005;
        public static final int background_light_transparent=0x7f040007;
        public static final int button_disabled=0x7f040015;
        public static final int button_enabled=0x7f040014;
        public static final int just_black=0x7f040001;
        public static final int just_white=0x7f040000;
        public static final int link=0x7f040013;
        public static final int separator_dark=0x7f040008;
        public static final int separator_light=0x7f040009;
        public static final int text_dark=0x7f04000b;
        public static final int text_grey_dark=0x7f04000f;
        public static final int text_grey_light=0x7f040010;
        public static final int text_headline_dark=0x7f04000d;
        public static final int text_headline_light=0x7f04000e;
        public static final int text_hint_dark=0x7f040011;
        public static final int text_hint_light=0x7f040012;
        public static final int text_icon=0x7f04000a;
        public static final int text_light=0x7f04000c;
    }
    public static final class dimen {
        public static final int title_height=0x7f050000;
    }
    public static final class drawable {
        public static final int action_button_dark=0x7f020000;
        public static final int action_button_dark_default=0x7f020001;
        public static final int action_button_dark_dialog=0x7f020002;
        public static final int action_button_dark_off=0x7f020003;
        public static final int action_button_dark_pressed=0x7f020004;
        public static final int action_button_light=0x7f020005;
        public static final int action_button_light_default=0x7f020006;
        public static final int action_button_light_dialog=0x7f020007;
        public static final int action_button_light_off=0x7f020008;
        public static final int action_button_light_pressed=0x7f020009;
        public static final int bcg_dark=0x7f02000a;
        public static final int bcg_dialog_dark=0x7f02000b;
        public static final int bcg_dialog_light=0x7f02000c;
        public static final int bcg_light=0x7f02000d;
        public static final int cache_dark=0x7f02000e;
        public static final int cache_dark_pressed=0x7f02000f;
        public static final int cache_light=0x7f020010;
        public static final int cache_light_pressed=0x7f020011;
        public static final int cgeo=0x7f020012;
        public static final int client_cgeo=0x7f020013;
        public static final int client_handygeocaching=0x7f020014;
        public static final int client_precaching=0x7f020015;
        public static final int compass_arrow=0x7f020016;
        public static final int compass_arrow_mini_black=0x7f020017;
        public static final int compass_arrow_mini_white=0x7f020018;
        public static final int compass_overlay=0x7f020019;
        public static final int compass_rose=0x7f02001a;
        public static final int compass_underlay=0x7f02001b;
        public static final int count_bcg=0x7f02001c;
        public static final int dialog_button_dark=0x7f02001d;
        public static final int dialog_button_light=0x7f02001e;
        public static final int helper_bcg=0x7f02001f;
        public static final int hw_menu=0x7f020020;
        public static final int icon_bcg=0x7f020021;
        public static final int icon_big=0x7f020022;
        public static final int image_no_placement=0x7f020023;
        public static final int image_not_loaded=0x7f020024;
        public static final int input_bcg_dark=0x7f020025;
        public static final int input_bcg_light=0x7f020026;
        public static final int inventory_background_dark=0x7f020027;
        public static final int inventory_background_light=0x7f020028;
        public static final int main_about=0x7f020029;
        public static final int main_any=0x7f02002a;
        public static final int main_filter=0x7f02002b;
        public static final int main_live=0x7f02002c;
        public static final int main_nearby=0x7f02002d;
        public static final int main_search=0x7f02002e;
        public static final int main_settings=0x7f02002f;
        public static final int main_stored=0x7f020030;
        public static final int map_close_dark=0x7f020031;
        public static final int map_close_light=0x7f020032;
        public static final int map_status_dark=0x7f020033;
        public static final int map_status_light=0x7f020034;
        public static final int mark_green=0x7f020035;
        public static final int mark_orange=0x7f020036;
        public static final int mark_red=0x7f020037;
        public static final int mark_red_more=0x7f020038;
        public static final int marker=0x7f020039;
        public static final int marker_cache_ape=0x7f02003a;
        public static final int marker_cache_ape_disabled=0x7f02003b;
        public static final int marker_cache_ape_found=0x7f02003c;
        public static final int marker_cache_cito=0x7f02003d;
        public static final int marker_cache_cito_disabled=0x7f02003e;
        public static final int marker_cache_cito_found=0x7f02003f;
        public static final int marker_cache_earth=0x7f020040;
        public static final int marker_cache_earth_disabled=0x7f020041;
        public static final int marker_cache_earth_found=0x7f020042;
        public static final int marker_cache_event=0x7f020043;
        public static final int marker_cache_event_disabled=0x7f020044;
        public static final int marker_cache_event_found=0x7f020045;
        public static final int marker_cache_letterbox=0x7f020046;
        public static final int marker_cache_letterbox_disabled=0x7f020047;
        public static final int marker_cache_letterbox_found=0x7f020048;
        public static final int marker_cache_locationless=0x7f020049;
        public static final int marker_cache_locationless_disabled=0x7f02004a;
        public static final int marker_cache_locationless_found=0x7f02004b;
        public static final int marker_cache_mega=0x7f02004c;
        public static final int marker_cache_mega_disabled=0x7f02004d;
        public static final int marker_cache_mega_found=0x7f02004e;
        public static final int marker_cache_multi=0x7f02004f;
        public static final int marker_cache_multi_disabled=0x7f020050;
        public static final int marker_cache_multi_found=0x7f020051;
        public static final int marker_cache_mystery=0x7f020052;
        public static final int marker_cache_mystery_disabled=0x7f020053;
        public static final int marker_cache_mystery_found=0x7f020054;
        public static final int marker_cache_traditional=0x7f020055;
        public static final int marker_cache_traditional_disabled=0x7f020056;
        public static final int marker_cache_traditional_found=0x7f020057;
        public static final int marker_cache_virtual=0x7f020058;
        public static final int marker_cache_virtual_disabled=0x7f020059;
        public static final int marker_cache_virtual_found=0x7f02005a;
        public static final int marker_cache_webcam=0x7f02005b;
        public static final int marker_cache_webcam_disabled=0x7f02005c;
        public static final int marker_cache_webcam_found=0x7f02005d;
        public static final int marker_cache_wherigo=0x7f02005e;
        public static final int marker_cache_wherigo_disabled=0x7f02005f;
        public static final int marker_cache_wherigo_found=0x7f020060;
        public static final int marker_waypoint_flag=0x7f020061;
        public static final int marker_waypoint_pkg=0x7f020062;
        public static final int marker_waypoint_puzzle=0x7f020063;
        public static final int marker_waypoint_stage=0x7f020064;
        public static final int marker_waypoint_trailhead=0x7f020065;
        public static final int marker_waypoint_waypoint=0x7f020066;
        public static final int my_location=0x7f020067;
        public static final int my_location_arrow=0x7f020068;
        public static final int my_location_chevron=0x7f020069;
        public static final int my_location_off=0x7f02006a;
        public static final int my_location_on=0x7f02006b;
        public static final int separator_dark=0x7f02006c;
        public static final int separator_light=0x7f02006d;
        public static final int star_half=0x7f02006e;
        public static final int star_off=0x7f02006f;
        public static final int star_on=0x7f020070;
        public static final int trackable_all=0x7f020071;
        public static final int trackable_coin=0x7f020072;
        public static final int trackable_coins=0x7f020073;
        public static final int trackable_tb=0x7f020074;
        public static final int trackable_tbs=0x7f020075;
        public static final int type_ape=0x7f020076;
        public static final int type_cito=0x7f020077;
        public static final int type_earth=0x7f020078;
        public static final int type_event=0x7f020079;
        public static final int type_letterbox=0x7f02007a;
        public static final int type_locationless=0x7f02007b;
        public static final int type_mega=0x7f02007c;
        public static final int type_multi=0x7f02007d;
        public static final int type_mystery=0x7f02007e;
        public static final int type_traditional=0x7f02007f;
        public static final int type_virtual=0x7f020080;
        public static final int type_webcam=0x7f020081;
        public static final int type_wherigo=0x7f020082;
        public static final int user_location=0x7f020083;
        public static final int user_location_active=0x7f020084;
        public static final int waypoint_flag=0x7f020085;
        public static final int waypoint_pkg=0x7f020086;
        public static final int waypoint_puzzle=0x7f020087;
        public static final int waypoint_stage=0x7f020088;
        public static final int waypoint_trailhead=0x7f020089;
        public static final int waypoint_waypoint=0x7f02008a;
    }
    public static final class id {
        public static final int about_go4cache=0x7f08004e;
        public static final int about_twitter=0x7f080050;
        public static final int action=0x7f080097;
        public static final int add_waypoint=0x7f08003c;
        public static final int added=0x7f08005e;
        public static final int addition=0x7f080044;
        public static final int address=0x7f08000e;
        public static final int address_list=0x7f08000a;
        public static final int advanced_button=0x7f080069;
        public static final int any_button=0x7f08006a;
        public static final int attributes=0x7f080034;
        public static final int attributes_box=0x7f080033;
        public static final int author=0x7f080002;
        public static final int authorize_twitter=0x7f080051;
        public static final int autoload=0x7f08005b;
        public static final int bearing=0x7f08007b;
        public static final int browser=0x7f08005d;
        public static final int button=0x7f080009;
        public static final int button_map=0x7f080008;
        public static final int checkbox=0x7f08001f;
        public static final int clear=0x7f080096;
        public static final int close=0x7f080073;
        public static final int close_dst=0x7f080074;
        public static final int close_gc=0x7f080075;
        public static final int compass=0x7f08007c;
        public static final int count=0x7f080060;
        public static final int current=0x7f08007a;
        public static final int date=0x7f080087;
        public static final int delete=0x7f08009a;
        public static final int desc_box=0x7f080036;
        public static final int description=0x7f080038;
        public static final int destination=0x7f080077;
        public static final int details=0x7f08008f;
        public static final int details_box=0x7f08008e;
        public static final int details_list=0x7f08002e;
        public static final int details_list_box=0x7f08002d;
        public static final int direction=0x7f08002a;
        public static final int directoryimg=0x7f08005a;
        public static final int disabled=0x7f080056;
        public static final int disabled_mark=0x7f080062;
        public static final int display_geocode=0x7f080011;
        public static final int display_trackable=0x7f080019;
        public static final int distance=0x7f080029;
        public static final int dnf_mark=0x7f080061;
        public static final int donation_less=0x7f080001;
        public static final int donation_more=0x7f080000;
        public static final int edit=0x7f08009b;
        public static final int exclude=0x7f080055;
        public static final int facebook=0x7f080005;
        public static final int filename=0x7f080048;
        public static final int filepath=0x7f080047;
        public static final int filter_button=0x7f08006b;
        public static final int filter_button_title=0x7f08006c;
        public static final int found_mark=0x7f080021;
        public static final int geocode=0x7f080010;
        public static final int gnav=0x7f080059;
        public static final int goal=0x7f08008d;
        public static final int goal_box=0x7f08008c;
        public static final int graphic=0x7f080007;
        public static final int heading=0x7f080078;
        public static final int helper=0x7f08006d;
        public static final int hint=0x7f08003e;
        public static final int hint_box=0x7f08003d;
        public static final int identification=0x7f080098;
        public static final int image=0x7f080091;
        public static final int image_box=0x7f080090;
        public static final int info=0x7f08002b;
        public static final int inventory=0x7f08002c;
        public static final int inventory_box=0x7f080035;
        public static final int keyword=0x7f080012;
        public static final int latitude=0x7f08000b;
        public static final int legal_note=0x7f08004a;
        public static final int livelist=0x7f08005c;
        public static final int log=0x7f080063;
        public static final int log_box=0x7f08003f;
        public static final int log_list=0x7f080040;
        public static final int log_me_in=0x7f08004c;
        public static final int log_visit=0x7f080082;
        public static final int log_visit_box=0x7f080081;
        public static final int longitude=0x7f08000c;
        public static final int mainscreen=0x7f080064;
        public static final int map=0x7f080065;
        public static final int map_ext=0x7f08009c;
        public static final int map_image=0x7f080049;
        public static final int maps_list=0x7f080085;
        public static final int more_caches=0x7f080045;
        public static final int more_details=0x7f080080;
        public static final int more_details_box=0x7f08007f;
        public static final int my_position=0x7f080076;
        public static final int name=0x7f080041;
        public static final int nav_accuracy=0x7f080070;
        public static final int nav_location=0x7f08006e;
        public static final int nav_satellites=0x7f080071;
        public static final int nav_type=0x7f08006f;
        public static final int navigation_part=0x7f080083;
        public static final int nearest=0x7f080066;
        public static final int note=0x7f080099;
        public static final int number=0x7f080072;
        public static final int offline=0x7f080057;
        public static final int offline_box=0x7f08002f;
        public static final int offline_count=0x7f080068;
        public static final int offline_mark=0x7f080022;
        public static final int offline_refresh=0x7f080031;
        public static final int offline_store=0x7f080032;
        public static final int offline_text=0x7f080030;
        public static final int one_cache=0x7f08001d;
        public static final int one_checkbox=0x7f08001e;
        public static final int one_info=0x7f080020;
        public static final int owner=0x7f080016;
        public static final int passvote=0x7f08004d;
        public static final int password=0x7f08004b;
        public static final int picker=0x7f080046;
        public static final int pin=0x7f08001a;
        public static final int pin_button=0x7f08001b;
        public static final int post=0x7f08008b;
        public static final int publicloc=0x7f08004f;
        public static final int radar=0x7f08007d;
        public static final int rating_mark_1=0x7f080027;
        public static final int rating_mark_2=0x7f080026;
        public static final int rating_mark_3=0x7f080025;
        public static final int rating_mark_4=0x7f080024;
        public static final int rating_mark_5=0x7f080023;
        public static final int rose=0x7f080079;
        public static final int save=0x7f080095;
        public static final int search_address=0x7f08000f;
        public static final int search_coordinates=0x7f08000d;
        public static final int search_keyword=0x7f080013;
        public static final int search_offline=0x7f080067;
        public static final int search_owner=0x7f080017;
        public static final int search_username=0x7f080015;
        public static final int shortdesc=0x7f080037;
        public static final int show_description=0x7f080039;
        public static final int signature=0x7f080053;
        public static final int skin=0x7f080054;
        public static final int spoiler_image=0x7f080092;
        public static final int spoiler_list=0x7f080086;
        public static final int stars=0x7f080043;
        public static final int start=0x7f08001c;
        public static final int support=0x7f080003;
        public static final int text=0x7f080028;
        public static final int title=0x7f080084;
        public static final int trackable=0x7f080018;
        public static final int trackable_list=0x7f080093;
        public static final int tracking=0x7f080088;
        public static final int turn=0x7f08007e;
        public static final int tweet=0x7f08008a;
        public static final int tweet_box=0x7f080089;
        public static final int twitter=0x7f080006;
        public static final int twitter_option=0x7f080052;
        public static final int type=0x7f08005f;
        public static final int types_list=0x7f080094;
        public static final int units=0x7f080058;
        public static final int username=0x7f080014;
        public static final int value=0x7f080042;
        public static final int waypoints=0x7f08003b;
        public static final int waypoints_box=0x7f08003a;
        public static final int website=0x7f080004;
    }
    public static final class layout {
        public static final int about_dark=0x7f030000;
        public static final int about_light=0x7f030001;
        public static final int address_button_dark=0x7f030002;
        public static final int address_button_light=0x7f030003;
        public static final int addresses_dark=0x7f030004;
        public static final int addresses_light=0x7f030005;
        public static final int advsearch_dark=0x7f030006;
        public static final int advsearch_light=0x7f030007;
        public static final int auth_dark=0x7f030008;
        public static final int auth_light=0x7f030009;
        public static final int cache_dark=0x7f03000a;
        public static final int cache_light=0x7f03000b;
        public static final int cachedetail_dark=0x7f03000c;
        public static final int cachedetail_light=0x7f03000d;
        public static final int cacheitem_dark=0x7f03000e;
        public static final int cacheitem_dark_layout=0x7f03000f;
        public static final int cacheitem_light=0x7f030010;
        public static final int cacheitem_light_layout=0x7f030011;
        public static final int caches_dark=0x7f030012;
        public static final int caches_footer_dark=0x7f030013;
        public static final int caches_footer_light=0x7f030014;
        public static final int caches_light=0x7f030015;
        public static final int date_dark=0x7f030016;
        public static final int date_light=0x7f030017;
        public static final int gpx_dark=0x7f030018;
        public static final int gpx_light=0x7f030019;
        public static final int gpxes_dark=0x7f03001a;
        public static final int gpxes_light=0x7f03001b;
        public static final int imgitem_dark=0x7f03001c;
        public static final int imgitem_light=0x7f03001d;
        public static final int init_dark=0x7f03001e;
        public static final int init_light=0x7f03001f;
        public static final int logitem_dark=0x7f030020;
        public static final int logitem_light=0x7f030021;
        public static final int main_transparent_all=0x7f030022;
        public static final int map_dark=0x7f030023;
        public static final int map_light=0x7f030024;
        public static final int navigate_dark=0x7f030025;
        public static final int navigate_light=0x7f030026;
        public static final int point_dark=0x7f030027;
        public static final int point_light=0x7f030028;
        public static final int popup_dark=0x7f030029;
        public static final int popup_light=0x7f03002a;
        public static final int smapitem_dark=0x7f03002b;
        public static final int smapitem_light=0x7f03002c;
        public static final int smaps_dark=0x7f03002d;
        public static final int smaps_light=0x7f03002e;
        public static final int spoileritem_dark=0x7f03002f;
        public static final int spoileritem_light=0x7f030030;
        public static final int spoilers_dark=0x7f030031;
        public static final int spoilers_light=0x7f030032;
        public static final int star=0x7f030033;
        public static final int touch_dark=0x7f030034;
        public static final int touch_light=0x7f030035;
        public static final int trackable_button_dark=0x7f030036;
        public static final int trackable_button_light=0x7f030037;
        public static final int trackable_icon_dark=0x7f030038;
        public static final int trackable_icon_light=0x7f030039;
        public static final int trackabledetail_dark=0x7f03003a;
        public static final int trackabledetail_light=0x7f03003b;
        public static final int trackableimage_all=0x7f03003c;
        public static final int trackables_dark=0x7f03003d;
        public static final int trackables_light=0x7f03003e;
        public static final int types_button_dark=0x7f03003f;
        public static final int types_button_light=0x7f030040;
        public static final int types_dark=0x7f030041;
        public static final int types_light=0x7f030042;
        public static final int visit_dark=0x7f030043;
        public static final int visit_light=0x7f030044;
        public static final int visit_trackable_dark=0x7f030045;
        public static final int visit_trackable_light=0x7f030046;
        public static final int waypoint_dark=0x7f030047;
        public static final int waypoint_light=0x7f030048;
        public static final int waypointadd_dark=0x7f030049;
        public static final int waypointadd_light=0x7f03004a;
        public static final int waypointitem_dark=0x7f03004b;
        public static final int waypointitem_light=0x7f03004c;
    }
    public static final class string {
        public static final int about=0x7f060006;
        public static final int about_auth_1=0x7f0600f2;
        public static final int about_auth_2=0x7f0600f3;
        public static final int about_button=0x7f06006d;
        /**  about 
 about 
 about 
 about 
         */
        public static final int about_changelog=0x7f060074;
        public static final int about_detail=0x7f060076;
        public static final int about_donate=0x7f060075;
        public static final int about_donation_less=0x7f060077;
        public static final int about_donation_more=0x7f060078;
        public static final int about_go4cache=0x7f0600f0;
        public static final int about_text=0x7f0600e9;
        public static final int about_twitter=0x7f0600f1;
        public static final int advanced_search_button=0x7f06006a;
        /**  caches 
 caches 
 caches 
 caches 
         */
        public static final int all=0x7f060008;
        public static final int any_button=0x7f06006c;
        public static final int ape=0x7f060015;
        public static final int app_name=0x7f060000;
        public static final int app_name_compass=0x7f060001;
        public static final int auth_again=0x7f060097;
        public static final int auth_authorize=0x7f060095;
        public static final int auth_dialog_completed=0x7f06009d;
        public static final int auth_dialog_pin_message=0x7f06009c;
        public static final int auth_dialog_pin_title=0x7f06009b;
        public static final int auth_dialog_wait=0x7f06009a;
        public static final int auth_finish=0x7f060099;
        public static final int auth_pin_hint=0x7f060098;
        public static final int auth_start=0x7f060096;
        /**  auth 
 auth 
 auth 
 auth 
         */
        public static final int auth_twitter=0x7f060094;
        public static final int author=0x7f0600ea;
        /**  basics 
 basics 
 basics 
 basics 
         */
        public static final int cache=0x7f060002;
        public static final int cache_attributes=0x7f0600ad;
        public static final int cache_calendars=0x7f0600dc;
        public static final int cache_coordinates=0x7f0600db;
        public static final int cache_count_more=0x7f0600a0;
        /**  cache 
 cache 
 cache 
 cache 
         */
        public static final int cache_count_no=0x7f06009e;
        public static final int cache_count_one=0x7f06009f;
        public static final int cache_description=0x7f0600b0;
        public static final int cache_description_long=0x7f0600b1;
        public static final int cache_dialog_loading_description=0x7f0600b7;
        public static final int cache_dialog_loading_details=0x7f0600b6;
        public static final int cache_dialog_offline_drop_message=0x7f0600bb;
        public static final int cache_dialog_offline_drop_title=0x7f0600ba;
        public static final int cache_dialog_offline_save_message=0x7f0600b9;
        public static final int cache_dialog_offline_save_title=0x7f0600b8;
        public static final int cache_dialog_refresh_message=0x7f0600bd;
        public static final int cache_dialog_refresh_title=0x7f0600bc;
        public static final int cache_difficulty=0x7f0600d4;
        public static final int cache_distance=0x7f0600d3;
        public static final int cache_event=0x7f0600d9;
        public static final int cache_geocode=0x7f0600d1;
        public static final int cache_hidden=0x7f0600d8;
        public static final int cache_hint=0x7f0600b4;
        public static final int cache_inventory=0x7f0600ae;
        public static final int cache_location=0x7f0600da;
        public static final int cache_log_offline=0x7f0600af;
        public static final int cache_logs=0x7f0600b5;
        public static final int cache_menu_around=0x7f0600c8;
        public static final int cache_menu_browser=0x7f0600c5;
        public static final int cache_menu_compass=0x7f0600bf;
        public static final int cache_menu_details=0x7f0600ca;
        public static final int cache_menu_event=0x7f0600c9;
        public static final int cache_menu_map=0x7f0600c2;
        public static final int cache_menu_map_ext=0x7f0600c3;
        public static final int cache_menu_map_static=0x7f0600c4;
        public static final int cache_menu_navigate=0x7f0600be;
        public static final int cache_menu_radar=0x7f0600c1;
        public static final int cache_menu_spoilers=0x7f0600c7;
        public static final int cache_menu_tbt=0x7f0600c0;
        public static final int cache_menu_visit=0x7f0600c6;
        public static final int cache_offline=0x7f0600a1;
        public static final int cache_offline_drop=0x7f0600a3;
        public static final int cache_offline_not_ready=0x7f0600a6;
        public static final int cache_offline_refresh=0x7f0600a2;
        public static final int cache_offline_store=0x7f0600a4;
        public static final int cache_offline_stored=0x7f0600a5;
        public static final int cache_offline_time_about=0x7f0600a7;
        public static final int cache_offline_time_days=0x7f0600ac;
        public static final int cache_offline_time_hour=0x7f0600aa;
        public static final int cache_offline_time_hours=0x7f0600ab;
        public static final int cache_offline_time_mins=0x7f0600a8;
        public static final int cache_offline_time_mins_few=0x7f0600a9;
        public static final int cache_owner=0x7f0600d7;
        public static final int cache_rating=0x7f0600d6;
        public static final int cache_status=0x7f0600cb;
        public static final int cache_status_archived=0x7f0600ce;
        public static final int cache_status_disabled=0x7f0600cf;
        public static final int cache_status_found=0x7f0600cd;
        public static final int cache_status_offline_log=0x7f0600cc;
        public static final int cache_status_premium=0x7f0600d0;
        public static final int cache_terrain=0x7f0600d5;
        public static final int cache_type=0x7f0600d2;
        public static final int cache_waypoints=0x7f0600b2;
        public static final int cache_waypoints_add=0x7f0600b3;
        public static final int caches_more_caches=0x7f060072;
        public static final int caches_more_caches_no=0x7f060073;
        public static final int caches_nearby_button=0x7f060069;
        /**  caches 
 caches 
 caches 
 caches 
         */
        public static final int caches_no_cache=0x7f060071;
        /**  changelog 
         */
        public static final int changelog=0x7f0600f4;
        public static final int cito=0x7f060010;
        public static final int detail=0x7f060003;
        public static final int earth=0x7f06000f;
        public static final int err_application_no=0x7f06005a;
        public static final int err_auth_initialize=0x7f06005b;
        public static final int err_auth_process=0x7f06005c;
        public static final int err_cannot_log_visit=0x7f06005d;
        public static final int err_comm=0x7f060044;
        public static final int err_detail_cache=0x7f06004b;
        public static final int err_detail_cache_find=0x7f06004c;
        public static final int err_detail_cache_find_some=0x7f06004d;
        public static final int err_detail_cache_forgot=0x7f06004e;
        public static final int err_detail_cache_language=0x7f06004f;
        public static final int err_detail_no_map_static=0x7f060051;
        public static final int err_detail_no_spoiler=0x7f060050;
        public static final int err_detail_open=0x7f06004a;
        public static final int err_detail_still_refreshing=0x7f060054;
        public static final int err_detail_still_removing=0x7f060052;
        public static final int err_detail_still_saving=0x7f060053;
        public static final int err_drop=0x7f060048;
        public static final int err_init_cleared=0x7f06005e;
        public static final int err_license=0x7f060046;
        public static final int err_login=0x7f060042;
        public static final int err_navigation_no=0x7f060059;
        /**  errors 
 errors 
 errors 
 errors 
         */
        public static final int err_none=0x7f06003e;
        public static final int err_parse=0x7f060040;
        public static final int err_radar_generic=0x7f060058;
        public static final int err_radar_market=0x7f060057;
        public static final int err_radar_message=0x7f060056;
        public static final int err_radar_title=0x7f060055;
        public static final int err_server=0x7f060041;
        public static final int err_start=0x7f06003f;
        public static final int err_store=0x7f060047;
        public static final int err_title_problem=0x7f060049;
        public static final int err_unknown=0x7f060043;
        public static final int err_wrong=0x7f060045;
        public static final int event=0x7f06000d;
        public static final int event_fail=0x7f0600de;
        /**  event 
 event 
 event 
 event 
         */
        public static final int event_success=0x7f0600dd;
        public static final int facebook=0x7f0600ed;
        public static final int gchq=0x7f060016;
        public static final int gps=0x7f060017;
        public static final int graphic=0x7f0600ef;
        public static final int helper=0x7f060007;
        public static final int init_address=0x7f060089;
        public static final int init_autoload=0x7f060090;
        public static final int init_browser=0x7f060092;
        public static final int init_cleared=0x7f060093;
        public static final int init_directoryimg=0x7f06008f;
        public static final int init_disabled=0x7f06008b;
        public static final int init_exclude=0x7f06008a;
        public static final int init_gcvote=0x7f06007a;
        /**  init 
 init 
 init 
 init 
         */
        public static final int init_geocaching=0x7f060079;
        public static final int init_go4cache=0x7f06007b;
        public static final int init_go4cache_connect=0x7f060082;
        public static final int init_legal=0x7f060081;
        public static final int init_livelist=0x7f060091;
        public static final int init_login=0x7f060080;
        public static final int init_nav=0x7f06008e;
        public static final int init_offline=0x7f06008c;
        public static final int init_other=0x7f060086;
        public static final int init_passvote=0x7f06007f;
        public static final int init_password=0x7f06007e;
        public static final int init_signature=0x7f060085;
        public static final int init_skin=0x7f060087;
        public static final int init_transparent=0x7f060088;
        public static final int init_twitter=0x7f06007c;
        public static final int init_twitter_authorize=0x7f060083;
        public static final int init_twitter_publish=0x7f060084;
        public static final int init_units=0x7f06008d;
        public static final int init_username=0x7f06007d;
        /**  next things 
 next things 
 next things 
 next things 
         */
        public static final int legal_note=0x7f0600e8;
        public static final int letterbox=0x7f06000c;
        /**  main screen 
 main screen 
 main screen 
 main screen 
         */
        public static final int live_map_button=0x7f060068;
        public static final int loc_gps=0x7f060061;
        /**  location service 
 location service 
 location service 
 location service 
         */
        public static final int loc_last=0x7f06005f;
        public static final int loc_net=0x7f060060;
        public static final int loc_no_addr=0x7f060064;
        public static final int loc_sat=0x7f060062;
        public static final int loc_trying=0x7f060063;
        public static final int log_archived=0x7f06002b;
        public static final int log_attend=0x7f060024;
        public static final int log_attended=0x7f060025;
        public static final int log_disabled=0x7f060023;
        public static final int log_discovered=0x7f06002c;
        public static final int log_dnf=0x7f06001f;
        public static final int log_enabled=0x7f060022;
        /**  logs 
 logs 
 logs 
 logs 
         */
        public static final int log_found=0x7f06001e;
        public static final int log_grabbed=0x7f060027;
        public static final int log_maintenance=0x7f060029;
        public static final int log_needs=0x7f060028;
        public static final int log_new_archive=0x7f060034;
        public static final int log_new_attend=0x7f060035;
        public static final int log_new_attended=0x7f060036;
        public static final int log_new_discovered=0x7f06003c;
        public static final int log_new_dnf=0x7f060032;
        /**  new logs 
 new logs 
 new logs 
 new logs 
         */
        public static final int log_new_found=0x7f060031;
        public static final int log_new_grab=0x7f06003a;
        public static final int log_new_maintenance=0x7f060038;
        public static final int log_new_maintenance_owner=0x7f060039;
        public static final int log_new_note=0x7f060033;
        public static final int log_new_retrieve=0x7f06003b;
        public static final int log_new_review=0x7f06003d;
        public static final int log_new_webcam=0x7f060037;
        public static final int log_note=0x7f060020;
        public static final int log_published=0x7f060021;
        public static final int log_retrieved=0x7f060026;
        public static final int log_review=0x7f06002d;
        public static final int log_tb_drop=0x7f060030;
        public static final int log_tb_nothing=0x7f06002e;
        public static final int log_tb_visit=0x7f06002f;
        public static final int log_update=0x7f06002a;
        public static final int lostfound=0x7f060014;
        public static final int mega=0x7f06000e;
        /**  standard menu 
 standard menu 
 standard menu 
 standard menu 
         */
        public static final int menu_about=0x7f060065;
        public static final int menu_filter=0x7f060067;
        public static final int menu_settings=0x7f060066;
        public static final int multi=0x7f06000a;
        public static final int mystery=0x7f06000b;
        public static final int now_searching=0x7f060070;
        public static final int popup_log_visit=0x7f0600e0;
        /**  popup 
 popup 
 popup 
 popup 
         */
        public static final int popup_more=0x7f0600df;
        public static final int popup_navigation=0x7f0600e1;
        public static final int search=0x7f060004;
        public static final int settings=0x7f060005;
        public static final int settings_button=0x7f06006e;
        public static final int stored_caches_button=0x7f06006b;
        public static final int support=0x7f0600eb;
        public static final int traditional=0x7f060009;
        public static final int twitter=0x7f0600ee;
        public static final int type=0x7f06006f;
        public static final int virtual=0x7f060012;
        /**  visit 
 visit 
 visit 
 visit 
         */
        public static final int visit_tweet=0x7f0600e7;
        public static final int waypoint_bearing=0x7f0600e4;
        /**  waypoint 
 waypoint 
 waypoint 
 waypoint 
         */
        public static final int waypoint_custom=0x7f0600e2;
        public static final int waypoint_distance=0x7f0600e5;
        public static final int waypoint_my_coordinates=0x7f0600e3;
        public static final int waypoint_name=0x7f0600e6;
        public static final int webcam=0x7f060011;
        public static final int website=0x7f0600ec;
        public static final int wherigo=0x7f060013;
        /**  waypoints 
 waypoints 
 waypoints 
 waypoints 
         */
        public static final int wp_final=0x7f060018;
        public static final int wp_pkg=0x7f06001b;
        public static final int wp_puzzle=0x7f06001a;
        public static final int wp_stage=0x7f060019;
        public static final int wp_trailhead=0x7f06001c;
        public static final int wp_waypoint=0x7f06001d;
    }
    public static final class style {
        /**  PARTIAL definitions 
         */
        public static final int cgeo=0x7f070000;
        public static final int dialog_dark=0x7f070001;
        public static final int dialog_light=0x7f070002;
        /**  FULL definitions 
 mainscreen icon 
         */
        public static final int icon_mainscreen=0x7f070003;
        public static final int icon_mainscreen_count=0x7f070005;
        public static final int icon_mainscreen_text=0x7f070004;
        /**  current location 
         */
        public static final int location_current=0x7f070006;
        public static final int location_current_accuracy=0x7f070008;
        public static final int location_current_satellites=0x7f070009;
        public static final int location_current_type=0x7f070007;
    }
    public static final class styleable {
        /** Attributes that can be used with a cgCompassMini.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #cgCompassMini_skin carnero.cgeo:skin}</code></td><td></td></tr>
           </table>
           @see #cgCompassMini_skin
         */
        public static final int[] cgCompassMini = {
            0x7f010000
        };
        /**
          <p>This symbol is the offset where the {@link carnero.cgeo.R.attr#skin}
          attribute's value can be found in the {@link #cgCompassMini} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:skin
        */
        public static final int cgCompassMini_skin = 0;
    };
}
