/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package carnero.cgeo;

public final class R {
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int skin=0x7f010000;
    }
    public static final class color {
        public static final int button_disabled=0x7f040002;
        public static final int button_enabled=0x7f040001;
        public static final int link=0x7f040000;
    }
    public static final class drawable {
        public static final int action_button_dark=0x7f020000;
        public static final int action_button_dark_dialog=0x7f020001;
        public static final int action_button_dark_off=0x7f020002;
        public static final int action_button_dark_pressed=0x7f020003;
        public static final int action_button_light=0x7f020004;
        public static final int action_button_light_dialog=0x7f020005;
        public static final int action_button_light_off=0x7f020006;
        public static final int action_button_light_pressed=0x7f020007;
        public static final int bcg_dialog_dark=0x7f020008;
        public static final int bcg_dialog_light=0x7f020009;
        public static final int cgeo=0x7f02000a;
        public static final int compass_arrow=0x7f02000b;
        public static final int compass_arrow_mini_black=0x7f02000c;
        public static final int compass_arrow_mini_white=0x7f02000d;
        public static final int compass_overlay=0x7f02000e;
        public static final int compass_rose=0x7f02000f;
        public static final int compass_underlay=0x7f020010;
        public static final int icon_big=0x7f020011;
        public static final int icon_title=0x7f020012;
        public static final int image_not_loaded=0x7f020013;
        public static final int input_bcg_dark=0x7f020014;
        public static final int input_bcg_light=0x7f020015;
        public static final int inventory_background_dark=0x7f020016;
        public static final int inventory_background_light=0x7f020017;
        public static final int main_about=0x7f020018;
        public static final int main_settings=0x7f020019;
        public static final int map_close_dark=0x7f02001a;
        public static final int map_close_light=0x7f02001b;
        public static final int map_status_dark=0x7f02001c;
        public static final int map_status_light=0x7f02001d;
        public static final int mark_green=0x7f02001e;
        public static final int mark_red=0x7f02001f;
        public static final int mark_red_more=0x7f020020;
        public static final int marker=0x7f020021;
        public static final int marker_cache_ape=0x7f020022;
        public static final int marker_cache_ape_disabled=0x7f020023;
        public static final int marker_cache_ape_found=0x7f020024;
        public static final int marker_cache_cito=0x7f020025;
        public static final int marker_cache_cito_disabled=0x7f020026;
        public static final int marker_cache_cito_found=0x7f020027;
        public static final int marker_cache_earth=0x7f020028;
        public static final int marker_cache_earth_disabled=0x7f020029;
        public static final int marker_cache_earth_found=0x7f02002a;
        public static final int marker_cache_event=0x7f02002b;
        public static final int marker_cache_event_disabled=0x7f02002c;
        public static final int marker_cache_event_found=0x7f02002d;
        public static final int marker_cache_letterbox=0x7f02002e;
        public static final int marker_cache_letterbox_disabled=0x7f02002f;
        public static final int marker_cache_letterbox_found=0x7f020030;
        public static final int marker_cache_locationless=0x7f020031;
        public static final int marker_cache_locationless_disabled=0x7f020032;
        public static final int marker_cache_locationless_found=0x7f020033;
        public static final int marker_cache_mega=0x7f020034;
        public static final int marker_cache_mega_disabled=0x7f020035;
        public static final int marker_cache_mega_found=0x7f020036;
        public static final int marker_cache_multi=0x7f020037;
        public static final int marker_cache_multi_disabled=0x7f020038;
        public static final int marker_cache_multi_found=0x7f020039;
        public static final int marker_cache_mystery=0x7f02003a;
        public static final int marker_cache_mystery_disabled=0x7f02003b;
        public static final int marker_cache_mystery_found=0x7f02003c;
        public static final int marker_cache_traditional=0x7f02003d;
        public static final int marker_cache_traditional_disabled=0x7f02003e;
        public static final int marker_cache_traditional_found=0x7f02003f;
        public static final int marker_cache_virtual=0x7f020040;
        public static final int marker_cache_virtual_disabled=0x7f020041;
        public static final int marker_cache_virtual_found=0x7f020042;
        public static final int marker_cache_webcam=0x7f020043;
        public static final int marker_cache_webcam_disabled=0x7f020044;
        public static final int marker_cache_webcam_found=0x7f020045;
        public static final int marker_cache_wherigo=0x7f020046;
        public static final int marker_cache_wherigo_disabled=0x7f020047;
        public static final int marker_cache_wherigo_found=0x7f020048;
        public static final int marker_waypoint_flag=0x7f020049;
        public static final int marker_waypoint_pkg=0x7f02004a;
        public static final int marker_waypoint_puzzle=0x7f02004b;
        public static final int marker_waypoint_stage=0x7f02004c;
        public static final int marker_waypoint_trailhead=0x7f02004d;
        public static final int marker_waypoint_waypoint=0x7f02004e;
        public static final int my_location=0x7f02004f;
        public static final int my_location_arrow=0x7f020050;
        public static final int separator_details_dark=0x7f020051;
        public static final int separator_details_light=0x7f020052;
        public static final int star_half=0x7f020053;
        public static final int star_off=0x7f020054;
        public static final int star_on=0x7f020055;
        public static final int trackable_all=0x7f020056;
        public static final int trackable_coin=0x7f020057;
        public static final int trackable_coins=0x7f020058;
        public static final int trackable_tb=0x7f020059;
        public static final int trackable_tbs=0x7f02005a;
        public static final int type_ape=0x7f02005b;
        public static final int type_cito=0x7f02005c;
        public static final int type_earth=0x7f02005d;
        public static final int type_event=0x7f02005e;
        public static final int type_letterbox=0x7f02005f;
        public static final int type_locationless=0x7f020060;
        public static final int type_mega=0x7f020061;
        public static final int type_multi=0x7f020062;
        public static final int type_mystery=0x7f020063;
        public static final int type_traditional=0x7f020064;
        public static final int type_virtual=0x7f020065;
        public static final int type_webcam=0x7f020066;
        public static final int type_wherigo=0x7f020067;
        public static final int user_location=0x7f020068;
        public static final int user_location_active=0x7f020069;
        public static final int waypoint_flag=0x7f02006a;
        public static final int waypoint_pkg=0x7f02006b;
        public static final int waypoint_puzzle=0x7f02006c;
        public static final int waypoint_stage=0x7f02006d;
        public static final int waypoint_trailhead=0x7f02006e;
        public static final int waypoint_waypoint=0x7f02006f;
    }
    public static final class id {
        public static final int about_button=0x7f070054;
        public static final int about_go4cache=0x7f07003c;
        public static final int about_twitter=0x7f07003e;
        public static final int add_waypoint=0x7f07002a;
        public static final int added=0x7f07004c;
        public static final int address=0x7f07000b;
        public static final int address_list=0x7f070007;
        public static final int advanced_button=0x7f070052;
        public static final int author=0x7f070001;
        public static final int authorize_twitter=0x7f07003f;
        public static final int autoload=0x7f070048;
        public static final int bearing=0x7f070062;
        public static final int browser=0x7f07004a;
        public static final int button=0x7f070006;
        public static final int cgeo_version=0x7f070000;
        public static final int close=0x7f07005b;
        public static final int close_dst=0x7f07005c;
        public static final int close_gc=0x7f07005d;
        public static final int compass=0x7f070063;
        public static final int current=0x7f070061;
        public static final int date=0x7f070076;
        public static final int delete=0x7f07007d;
        public static final int desc_box=0x7f070024;
        public static final int description=0x7f070026;
        public static final int destination=0x7f07005e;
        public static final int details=0x7f070067;
        public static final int details_box=0x7f070070;
        public static final int details_list=0x7f070023;
        public static final int details_list_box=0x7f070022;
        public static final int details_part=0x7f070066;
        public static final int direction=0x7f07001f;
        public static final int directoryimg=0x7f070047;
        public static final int disabled=0x7f070043;
        public static final int disabled_mark=0x7f07004e;
        public static final int display_geocode=0x7f07000e;
        public static final int display_trackable=0x7f070016;
        public static final int distance=0x7f07001e;
        public static final int dnf_mark=0x7f07004d;
        public static final int edit=0x7f07007c;
        public static final int exclude=0x7f070042;
        public static final int facebook=0x7f070004;
        public static final int found_mark=0x7f07001c;
        public static final int geocode=0x7f07000d;
        public static final int gnav=0x7f070046;
        public static final int goal=0x7f07006f;
        public static final int goal_box=0x7f07006e;
        public static final int gps=0x7f07005a;
        public static final int heading=0x7f07005f;
        public static final int hint=0x7f07002c;
        public static final int hint_box=0x7f07002b;
        public static final int identification=0x7f070078;
        public static final int image=0x7f070072;
        public static final int image_box=0x7f070071;
        public static final int info=0x7f070020;
        public static final int inventory=0x7f070021;
        public static final int keyword=0x7f07000f;
        public static final int latitude=0x7f070008;
        public static final int legal_note=0x7f07003b;
        public static final int livelist=0x7f070049;
        public static final int log=0x7f07004f;
        public static final int log_box=0x7f07002f;
        public static final int log_list=0x7f070030;
        public static final int log_me_in=0x7f07003a;
        public static final int longitude=0x7f070009;
        public static final int map=0x7f070050;
        public static final int map_box=0x7f07002d;
        public static final int map_image=0x7f070038;
        public static final int map_list=0x7f07002e;
        public static final int more=0x7f07006a;
        public static final int more_caches=0x7f070036;
        public static final int more_part=0x7f070069;
        public static final int name=0x7f070031;
        public static final int nav_accuracy=0x7f070058;
        public static final int nav_location=0x7f070056;
        public static final int nav_satellites=0x7f070059;
        public static final int nav_type=0x7f070057;
        public static final int navigation_part=0x7f070068;
        public static final int nearest=0x7f070051;
        public static final int note=0x7f07007a;
        public static final int note_part=0x7f070079;
        public static final int offline=0x7f070044;
        public static final int offline_part=0x7f07006b;
        public static final int one_cache=0x7f07001b;
        public static final int operation_part=0x7f07007b;
        public static final int owner=0x7f070013;
        public static final int password=0x7f070039;
        public static final int picker=0x7f070037;
        public static final int pin=0x7f070019;
        public static final int pin_button=0x7f07001a;
        public static final int post=0x7f070077;
        public static final int publicloc=0x7f07003d;
        public static final int radar=0x7f070064;
        public static final int refresh=0x7f070034;
        public static final int rose=0x7f070060;
        public static final int search_address=0x7f07000c;
        public static final int search_coordinates=0x7f07000a;
        public static final int search_keyword=0x7f070010;
        public static final int search_offline=0x7f070053;
        public static final int search_owner=0x7f070014;
        public static final int search_username=0x7f070012;
        public static final int settings_button=0x7f070055;
        public static final int shortdesc=0x7f070025;
        public static final int show_description=0x7f070027;
        public static final int skin=0x7f070041;
        public static final int spoiler_image=0x7f070073;
        public static final int spoiler_list=0x7f07006d;
        public static final int stars=0x7f070033;
        public static final int start=0x7f070017;
        public static final int start_over=0x7f070018;
        public static final int store=0x7f070035;
        public static final int support=0x7f070002;
        public static final int text=0x7f07001d;
        public static final int title=0x7f07006c;
        public static final int trackable=0x7f070015;
        public static final int trackable_list=0x7f070074;
        public static final int turn=0x7f070065;
        public static final int twitter=0x7f070005;
        public static final int twitter_option=0x7f070040;
        public static final int type=0x7f07004b;
        public static final int types_list=0x7f070075;
        public static final int units=0x7f070045;
        public static final int username=0x7f070011;
        public static final int value=0x7f070032;
        public static final int waypoints=0x7f070029;
        public static final int waypoints_box=0x7f070028;
        public static final int website=0x7f070003;
    }
    public static final class layout {
        public static final int about_dark=0x7f030000;
        public static final int about_light=0x7f030001;
        public static final int address_button_dark=0x7f030002;
        public static final int address_button_light=0x7f030003;
        public static final int addresses_dark=0x7f030004;
        public static final int addresses_light=0x7f030005;
        public static final int advsearch_dark=0x7f030006;
        public static final int advsearch_light=0x7f030007;
        public static final int auth_dark=0x7f030008;
        public static final int auth_light=0x7f030009;
        public static final int cache_dark=0x7f03000a;
        public static final int cache_light=0x7f03000b;
        public static final int cachedetail_dark=0x7f03000c;
        public static final int cachedetail_light=0x7f03000d;
        public static final int cacheitem_dark=0x7f03000e;
        public static final int cacheitem_dark_first=0x7f03000f;
        public static final int cacheitem_dark_layout=0x7f030010;
        public static final int cacheitem_dark_offline=0x7f030011;
        public static final int cacheitem_light=0x7f030012;
        public static final int cacheitem_light_first=0x7f030013;
        public static final int cacheitem_light_layout=0x7f030014;
        public static final int cacheitem_light_offline=0x7f030015;
        public static final int caches_dark=0x7f030016;
        public static final int caches_footer_dark=0x7f030017;
        public static final int caches_footer_light=0x7f030018;
        public static final int caches_light=0x7f030019;
        public static final int date_dark=0x7f03001a;
        public static final int date_light=0x7f03001b;
        public static final int imgitem_dark=0x7f03001c;
        public static final int imgitem_light=0x7f03001d;
        public static final int init_dark=0x7f03001e;
        public static final int init_light=0x7f03001f;
        public static final int logitem_dark=0x7f030020;
        public static final int logitem_light=0x7f030021;
        public static final int main_dark=0x7f030022;
        public static final int main_light=0x7f030023;
        public static final int map_dark=0x7f030024;
        public static final int map_light=0x7f030025;
        public static final int navigate_dark=0x7f030026;
        public static final int navigate_light=0x7f030027;
        public static final int point_dark=0x7f030028;
        public static final int point_light=0x7f030029;
        public static final int popup_dark=0x7f03002a;
        public static final int popup_light=0x7f03002b;
        public static final int spoileritem_dark=0x7f03002c;
        public static final int spoileritem_light=0x7f03002d;
        public static final int spoilers_dark=0x7f03002e;
        public static final int spoilers_light=0x7f03002f;
        public static final int star=0x7f030030;
        public static final int trackable_button_dark=0x7f030031;
        public static final int trackable_button_light=0x7f030032;
        public static final int trackable_icon_dark=0x7f030033;
        public static final int trackable_icon_light=0x7f030034;
        public static final int trackabledetail_dark=0x7f030035;
        public static final int trackabledetail_light=0x7f030036;
        public static final int trackableimage_all=0x7f030037;
        public static final int trackables_dark=0x7f030038;
        public static final int trackables_light=0x7f030039;
        public static final int types_button_dark=0x7f03003a;
        public static final int types_button_light=0x7f03003b;
        public static final int types_dark=0x7f03003c;
        public static final int types_light=0x7f03003d;
        public static final int visit_dark=0x7f03003e;
        public static final int visit_light=0x7f03003f;
        public static final int waypoint_dark=0x7f030040;
        public static final int waypoint_light=0x7f030041;
        public static final int waypointadd_dark=0x7f030042;
        public static final int waypointadd_light=0x7f030043;
        public static final int waypointitem_dark=0x7f030044;
        public static final int waypointitem_light=0x7f030045;
    }
    public static final class string {
        public static final int about=0x7f050048;
        public static final int about_auth_1=0x7f050050;
        public static final int about_auth_2=0x7f050051;
        public static final int about_button=0x7f050040;
        public static final int about_go4cache=0x7f05004e;
        public static final int about_twitter=0x7f05004f;
        public static final int advanced_search_button=0x7f05003e;
        /**  caches 
         */
        public static final int all=0x7f050002;
        public static final int ape=0x7f05000f;
        public static final int app_name=0x7f050000;
        public static final int app_name_compass=0x7f050001;
        public static final int author=0x7f050049;
        public static final int caches_more_caches=0x7f050045;
        public static final int caches_more_caches_no=0x7f050046;
        public static final int caches_nearby_button=0x7f05003d;
        /**  caches 
         */
        public static final int caches_no_cache=0x7f050044;
        /**  changelog 
         */
        public static final int changelog=0x7f050052;
        public static final int cito=0x7f05000a;
        public static final int earth=0x7f050009;
        public static final int err_comm=0x7f050031;
        public static final int err_license=0x7f050033;
        public static final int err_login=0x7f05002f;
        /**  errors 
         */
        public static final int err_none=0x7f05002b;
        public static final int err_parse=0x7f05002d;
        public static final int err_server=0x7f05002e;
        public static final int err_start=0x7f05002c;
        public static final int err_unknown=0x7f050030;
        public static final int err_wrong=0x7f050032;
        public static final int event=0x7f050007;
        public static final int facebook=0x7f05004c;
        public static final int gchq=0x7f050010;
        public static final int gps=0x7f050011;
        /**  next things 
         */
        public static final int legal_note=0x7f050047;
        public static final int letterbox=0x7f050006;
        /**  main screen 
         */
        public static final int live_map_button=0x7f05003c;
        public static final int loc_gps=0x7f050036;
        /**  location service 
         */
        public static final int loc_last=0x7f050034;
        public static final int loc_net=0x7f050035;
        public static final int loc_sat=0x7f050037;
        public static final int loc_trying=0x7f050038;
        public static final int log_archived=0x7f050021;
        public static final int log_disabled=0x7f05001d;
        public static final int log_dnf=0x7f050019;
        public static final int log_enabled=0x7f05001c;
        /**  logs 
         */
        public static final int log_found=0x7f050018;
        public static final int log_maintenance=0x7f05001f;
        public static final int log_needs=0x7f05001e;
        public static final int log_new_archive=0x7f050026;
        public static final int log_new_attend=0x7f050027;
        public static final int log_new_attended=0x7f050028;
        public static final int log_new_dnf=0x7f050024;
        /**  new logs 
         */
        public static final int log_new_found=0x7f050023;
        public static final int log_new_maintenance=0x7f05002a;
        public static final int log_new_note=0x7f050025;
        public static final int log_new_webcam=0x7f050029;
        public static final int log_note=0x7f05001a;
        public static final int log_published=0x7f05001b;
        public static final int log_review=0x7f050022;
        public static final int log_update=0x7f050020;
        public static final int lostfound=0x7f05000e;
        public static final int mega=0x7f050008;
        /**  standard menu 
         */
        public static final int menu_about=0x7f050039;
        public static final int menu_any_destination=0x7f05003b;
        public static final int menu_settings=0x7f05003a;
        public static final int multi=0x7f050004;
        public static final int mystery=0x7f050005;
        public static final int now_searching=0x7f050043;
        public static final int settings_button=0x7f050041;
        public static final int stored_caches_button=0x7f05003f;
        public static final int support=0x7f05004a;
        public static final int traditional=0x7f050003;
        public static final int twitter=0x7f05004d;
        public static final int type=0x7f050042;
        public static final int virtual=0x7f05000c;
        public static final int webcam=0x7f05000b;
        public static final int website=0x7f05004b;
        public static final int wherigo=0x7f05000d;
        /**  waypoints 
         */
        public static final int wp_final=0x7f050012;
        public static final int wp_pkg=0x7f050015;
        public static final int wp_puzzle=0x7f050014;
        public static final int wp_stage=0x7f050013;
        public static final int wp_trailhead=0x7f050016;
        public static final int wp_waypoint=0x7f050017;
    }
    public static final class style {
        /**  <item name="android:windowNoTitle">true</item> 
         */
        public static final int cgeo=0x7f060000;
        public static final int dialog_dark=0x7f060001;
        public static final int dialog_light=0x7f060002;
    }
    public static final class styleable {
        /** Attributes that can be used with a cgCompassMini.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #cgCompassMini_skin carnero.cgeo:skin}</code></td><td></td></tr>
           </table>
           @see #cgCompassMini_skin
         */
        public static final int[] cgCompassMini = {
            0x7f010000
        };
        /**
          <p>This symbol is the offset where the {@link carnero.cgeo.R.attr#skin}
          attribute's value can be found in the {@link #cgCompassMini} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:skin
        */
        public static final int cgCompassMini_skin = 0;
    };
}
